FROM nginx:latest

RUN sed -i '/error_page.*404/a \
\
    add_header X-XSS-Protection "0"; \
    add_header Access-Control-Allow-Origin "*"; \
    add_header Access-Control-Allow-Headers "X-PINGOTHER, Content-Type"; \
\
    location ~ \\.php$ { \
        root           \/var\/www\/html; \
        fastcgi_pass   php_net:9000; \
        fastcgi_index  index.php; \
	fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name; \
        include        fastcgi_params; \
    }' /etc/nginx/conf.d/default.conf; \
    sed -i 's/index.html/index.php/g' /etc/nginx/conf.d/default.conf; 

WORKDIR /usr/share/nginx/html

RUN apt-get update; \
	apt-get install -y git; \
	git clone https://github.com/slee96/SQL-Injection-XSS-scripting-examples.git; \
	mv SQL-Injection-XSS-scripting-examples/travel.cmdctrl.ca/* .; \
	rm -rf index.html SQL-Injection-XSS-scripting-examples *.php; \
	touch index.php;


CMD ["nginx", "-g", "daemon off;"]
